In [1]:
import numpy as np

In [2]:
x = np.array([1, 4, 3, 1])

In [3]:
p = np.exp(x)
p

array([ 2.71828183, 54.59815003, 20.08553692,  2.71828183])

In [4]:
p/p.sum()

array([0.03392753, 0.68145256, 0.25069239, 0.03392753])

# Stable

In [5]:
p = np.exp(x - x.max())
p

array([0.04978707, 1.        , 0.36787944, 0.04978707])

In [6]:
p/p.sum()

array([0.03392753, 0.68145256, 0.25069239, 0.03392753])

# Digression

## Streaming Normalization

In [25]:
data = np.random.randn(1024)
weights = np.random.rand(1024)

z = weights.sum()
(data * weights/z).sum()

-0.11346321688616925

In [26]:
acc = 0
z = 0

for d, w in zip(data, weights):
    acc += w*d
    z += w
acc/z

-0.1134632168861692

## Exp

In [27]:
weights *= 100
z = np.exp(weights).sum()
(data * np.exp(weights)/z).sum()

-0.46750761319361334

In [36]:
z = np.exp(weights).sum()
(data * np.exp(weights)/z).sum()

-0.46750761319361334

In [37]:
# Numerically Stable Approach

apriory_known_max = weights.max()
acc = 0
z = 0

for d, w in zip(data, weights):
    acc += np.exp(w-apriory_known_max)*d
    z += np.exp(w-apriory_known_max)
acc/z

-0.4675076131936131

In [29]:
# Don't know the apriory_known_max

acc = 0
z = 0
m = float('-inf')

for d, w in zip(data, weights):
    new_m = max(m, w)
    acc = acc*z + np.exp(w - new_m)*d
    z = z*
    # z += np.exp(w-apriory_known_max)
acc/z


(1024,)